title: Samuel Pulido
#image: 
description: Data Analyst with a strong background in problem-solving, automation, and visualization. Experienced in leveraging Python, SQL, and Power BI to drive insights and optimize decision-making processes. Proven ability to transform manual workflows into efficient, automated systems.
show_downloads: true
theme: jekyll_theme_minimal
